sudo: required
dist: xenial
before_install:
- sudo add-apt-repository -y ppa:jonathonf/texlive
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-xetex texlive texlive-lang-german texlive-latex-extra texlive-latex-recommended texlive-pictures
script:
- mkdir _build
- xelatex -interaction=nonstopmode -halt-on-error -output-directory _build statuten.tex

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: release
