sudo: required
dist: trusty
before_install:
  - sudo apt-get install pandoc wkhtml2pdf
script:
  - pandoc --standalone -t html5 --template template.html5 statuten.md -o statuten.html
  -

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: release
