sudo: required
dist: trusty
before_install:
  - sudo apt-get install pandoc
script:
  - mkdir _build
  - 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: release
