sudo: required
dist: xenial
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive texlive-lang-german texlive-doc-de texlive-latex-extra
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build statuten.tex

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: release
